### ISSUE TITLE
Can connect with chrome headless server?

### ISSUE THREAD

**Issue by bakatest-me** [geziyor/geziyor#10]

**Comment by musabgultekin** [comment]
Not yet, Thumbs up if you want me to implement this feature.

**Comment by musabgultekin** [comment]
Now implemented: https://github.com/geziyor/geziyor/commit/0e5230eac8f7c23322af2e3113c19063a6466b56

Just set BrowserEndpoint option to connect chrome headless server

**Comment by LeMoussel** [comment]
See #16
