### ISSUE TITLE
Question: Pass through data

### ISSUE THREAD

**Issue by pkmishra** [geziyor/geziyor#13]
What's the best way to implement pass through data e.g. from the top level I would like to pass tags which could be used while writing to file.

**Comment by musabgultekin** [comment]
Meta map can be used on requests. https://github.com/geziyor/geziyor/blob/master/client/request.go#L14
Is that what you'r looking for?

**Comment by pkmishra** [comment]
perfect. thank you so much.

**Comment by dbgrowth** [comment]
> Meta map can be used on requests. https://github.com/geziyor/geziyor/blob/master/client/request.go#L14
> Is that what you'r looking for?

Hi, Can you provide an example?
Thanks.

**Comment by pkmishra** [comment]
`
meta := make(map[string]interface{})     //set meta here
Get(g, <some url>, meta, g.Opt.ParseFunc){}
`
`
ParseFunc: func(g *geziyor.Geziyor, r *client.Response) {
m := r.Request.Meta //can be used to setup extra values.
}
`

**Comment by panikptz** [comment]
> `meta := make(map[string]interface{}) //set meta here Get(g, <some url>, meta, g.Opt.ParseFunc){}`
> `ParseFunc: func(g *geziyor.Geziyor, r *client.Response) { m := r.Request.Meta //can be used to setup extra values. }`

Please, can you give me a detailed example. The Get method is not clear to me.
Thanks.

**Comment by musabgultekin** [comment]
Hi @panikptz . I've added tests and documentation for passing data through requests. see d3bdaf6240124135397ae8ebaa08378ea1901a31

**Comment by panikptz** [comment]
@musabgultekin , this information really helped me, thanks a lot!
