### ISSUE TITLE
How to get response error other than HTTP errors

### ISSUE THREAD

**Issue by LeMoussel** [geziyor/geziyor#15]
Hi,

How can I get response error other than HTTP errors (StatusCode), like time out, address not found, Website isn't reachable.... ? 
For example
```
	geziyor.NewGeziyor(&geziyor.Options{
		StartURLs: []string{"http://www.1b4f.com/"},
		ParseFunc: func(g *geziyor.Geziyor, r *client.Response) {
			fmt.Println(string(r.Body))
		},
	}).Start()
```
 **Log output :**
> 2019/12/10 15:00:21 Scraping Started
> 2019/12/10 15:00:21 Retrying: http://www.1b4f.com/
> 2019/12/10 15:00:21 Retrying: http://www.1b4f.com/
> 2019/12/10 15:00:21 Response error: Get http://www.1b4f.com/: dial tcp: lookup www.1b4f.com: no such host
> 2019/12/10 15:00:21 Scraping Finished

I want to strore in DataBase site Url & Error ("http://www.1b4f.com/", "dial tcp: lookup www.1b4f.com: no such host")

**Comment by musabgultekin** [comment]
We could add error handler function on options. And calling that function on any error. Like this:

    ErrorFunc func(g *Geziyor, r *client.Request, err error)

Is that good?

**Comment by LeMoussel** [comment]
That sounds fine to me. 👍

**Comment by musabgultekin** [comment]
Implemented in: https://github.com/geziyor/geziyor/commit/cfb16fe1ee0e3d08452e6a9740e3738a8a81e277

	geziyor.NewGeziyor(&geziyor.Options{
		StartURLs: []string{"http://www.1b4f.com/"},
		ParseFunc: func(g *geziyor.Geziyor, r *client.Response) {
			fmt.Println(string(r.Body))
		},
		ErrorFunc: func(g *geziyor.Geziyor, r *client.Request, err error) {
			fmt.Println("Holaa", err)
		},
	}).Start()

**Comment by musabgultekin** [comment]
ErrorFunc called on any errors. Closing.
