### ISSUE TITLE
The beauty of geziyor

### ISSUE THREAD

**Issue by Ouch** [geziyor/geziyor#17]
Hello,

I'm doing a small interview with those who have been rising in Go works, and have began to make a name for themselves, and wanted to discuss where the very creative and stunning name 'geziyor' came from, and what prompted the creative talent to use it? Is it a personal preference, or was it a sudden come to mind thought to use? 

It's quite provocative and sends a strong battle cry feeling when said, as stated by one of our interns, and wanted to know if it had a type of medieval take. Have you / y'all thought of other names in previous times, and what were other choices if you had?

Is geziyor an online identity, or does it stem further into a construction of meaning and brought together by the talent working behind it?  

Thank you,
Ouch

**Comment by musabgultekin** [comment]
Hi,
Thanks for your kind words.
Geziyor means "travelling" in Turkish language. The project is related to visiting multiple pages. So, there is meaning behind this choice :)
I didn't think its english pronunciation, I just liked its meaning and relation of this project. I hear from you "Strong battle feel" first time, but its true :)
