### ISSUE TITLE
Comparison to GoColly 

### ISSUE THREAD

**Issue by rainbowhat** [geziyor/geziyor#2]
Hi @musabgultekin ,

What do you intent to do to differentiate this to GoColly? 
Do you have any plans for the crawler to listen to a queue ? Or some form of road map

**Comment by musabgultekin** [comment]
I want to make this extensible and flexible to be used in big projects. Such as
- Command line tool for: pausing and resuming scraper etc.
- Automatic item extractors (like rules)
- Deploying Scrapers to Cloud
- Automatically exporting extracted data in multiple places (AWS, FTP, DB, JSON, CSV etc)
- Downloading media (Images, Videos etc)
What

**Comment by musabgultekin** [comment]
I've added roadmap to README. Closing now.
