### ISSUE TITLE
Not correctly exporting JSON-format

### ISSUE THREAD

**Issue by ronbarhash** [geziyor/geziyor#21]
When forming (exporting), JSON does not correctly execute the method WriteAt 
 https://github.com/geziyor/geziyor/blob/cfb16fe1ee0e3d08452e6a9740e3738a8a81e277/export/json.go#L77

if you remove O_APPEND flag in [line](https://github.com/geziyor/geziyor/blob/master/export/json.go#L52), the [WriteAt](https://pkg.go.dev/os#File.WriteAt) method will work correctly

**Comment by musabgultekin** [comment]
Fixed here: https://github.com/geziyor/geziyor/commit/46c4db6b1a0ba507a186b0d491a1cd5d1e485ed6
