### ISSUE TITLE
go get geziyor has error

### ISSUE THREAD

**Issue by prr123** [geziyor/geziyor#22]
the problem is that go get gezibor relies on github/knq/sysutil. The module's path was modified resulting in the error message:
github,com/knq/sysutil parsing go.mod
module declares its path as: github.com/chromedp/sysutil
but was required as: github.com/knq/sysutil

This should a simple correction.

**Comment by musabgultekin** [comment]
I updated modules, It should be fixed. Can you confirm it fixed?

**Comment by prr123** [comment]
I performed an installation today and it seems to work fine.

**Comment by prr123** [comment]
thank you for the fix
