### ISSUE TITLE
Proxy Management Not supported 

### ISSUE THREAD

**Issue by prashant-ee** [geziyor/geziyor#23]
In order to integrate proxies, geziyor does not provide any interface. It does provide request middlewares but the object that can be manipulated in the middleware does not have proxy related configuration. Would be great if that can be supported as well.

**Comment by musabgultekin** [comment]
Geziyor currently only supports proxy from env variables from HTTP_PROXY and HTTPS_PROXY. Do you need something like changing proxy for every request?

**Comment by prashant-ee** [comment]
> Geziyor currently only supports proxy from env variables from HTTP_PROXY and HTTPS_PROXY. Do you need something like changing proxy for every request?

Yes, exactly. I wanted to use different proxy for different requests.

**Comment by musabgultekin** [comment]
I'm so sorry its too late but I've implemented the exact behaviour you wanted. Its here: https://github.com/geziyor/geziyor/pull/37
If you want to review, so good, if not I'll merge it.

**Comment by musabgultekin** [comment]
Merged: https://github.com/geziyor/geziyor/pull/37
