### ISSUE TITLE
client: use external http.Client or use external cookies

### ISSUE THREAD

**Issue by fabstu** [geziyor/geziyor#24]
I have already retrieved cookies with a different http.Client and would like to use these cookies or that http.Client for crawling. How do I set this up? In `StartRequestsFunc` I tried:

```go
g.Client.Client = httpClient
```

```go
g.Client.SetCookies(baseURL, cookies)
```

```go
g.Client.Jar.SetCookies(baseURL, cookies)
```

In all three cases I was redirected to the login screen. Did I set the cookies wrong or is it usually done a different way? With `httpClient`the retrieval of the site works but just without JS, which I try to fix with your awesome library. As `baseURL` I passed one time the base URL of the website and once the exact URL I am querying.

EDIT: I might have to check whether its due to a different UserAgent.

**Comment by musabgultekin** [comment]
g.Client is not used for js requests. Its only used for non-js requests.

Added tests/guide for setting cookies for rendered requests. 
https://github.com/geziyor/geziyor/commit/242b025c9a056065b2575e8fe55773dd1b7e8493
