### ISSUE TITLE
LogDisabled scope of action need to be restricted to Gezior only

### ISSUE THREAD

**Issue by Edlundin** [geziyor/geziyor#25]
Hi,

Geziyor's log disabling feature needs to be restricted to Geziyor only. Using the `LogDisabled` option currently makes you unable to hide Gezior's logs **and** use the Golang built-in logger.

I believe this bit of code is the culprit since it's discarding everything fed to the built-in logger:

https://github.com/geziyor/geziyor/blob/129402d754a645af843e5fc04cc6e100c203ef61/geziyor.go#L119-L124

Best regards,
E. Lundin.

**Comment by musabgultekin** [comment]
Thanks for pointing that out. I just implemented a custom logger for geziyor only. see e3d79e2

**Comment by Edlundin** [comment]
Oh, that was quick!
Many thanks for your work!
