### ISSUE TITLE
Is there a way to use chromedp's ListenTarget with geziyor?

### ISSUE THREAD

**Issue by ThomasMeetKai** [geziyor/geziyor#26]
https://pkg.go.dev/github.com/chromedp/chromedp?utm_source=godoc#ListenTarget

Something similar is available with puppeteer. I'd also like to be able to disable images from being loaded like this: https://github.com/chromedp/chromedp/issues/260

I guess basically, how do you access the chromedp context for geziyor requests?

**Comment by musabgultekin** [comment]
Hi, does overriding chromedp context allows to use this ? For example, If we allow using custom context instead of creating new here: https://github.com/geziyor/geziyor/blob/d3bdaf6240124135397ae8ebaa08378ea1901a31/client/client.go#L169
does that function the way you want to do?

**Comment by ThomasMeetKai** [comment]
It might, I'll investigate, but I think we might actually just end up using puppeteer for this. Thanks for pointing me in that direction though!
