### ISSUE TITLE
google-chrome: executable file not found in $PATH

### ISSUE THREAD

**Issue by dock-mausbach** [geziyor/geziyor#27]
### Issue: 

I get an error when I start my service on the server. Local on my machine everything works so far.

`request getting rendered: exec: "google-chrome": executable file not found in $PATH`

### Code

main.go
```Go
// ...
	crawler := geziyor.NewGeziyor(&geziyor.Options{
		StartRequestsFunc: func(g *geziyor.Geziyor) {
			g.GetRendered("https://www.google.com/", g.Opt.ParseFunc)
		},
		Exporters: []export.Exporter{&export.JSON{}},
	})
	
	crawler.Start()
// ...
```

Dockerfile
```Dockerfile
# -- Stage 1 -- #
FROM golang:1.16-alpine as builder
WORKDIR /app

COPY . .
RUN go build -mod=readonly -o bin/service

# -- Stage 2 -- #
FROM alpine

# Install any required dependencies.
RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/bin/service /usr/local/bin/

CMD ["service"]
```
### Question

I assume I need additional dependencies on my server for geziyor to run smoothly? For example Headless Chrome?

**Comment by musabgultekin** [comment]
Yes, google chrome binary is needed for js rendered requests. I didn't use js rendering in docker image before. So I haven't tested but something like this https://github.com/Zenika/alpine-chrome should work. I'll test it and possibly add it to the README file when I got time.

**Comment by dock-mausbach** [comment]
Thank you for your answer. All right, I'll take a look too.

**Comment by dock-mausbach** [comment]
I have tried to add Chromium as a dependency. But unfortunately without success so far, although the error message `google-chrome: executable not found in $PATH` has disappeared. It did start `Scraping Started` but it does not finish. Unfortunately, the log does not say anything else.

Any idea what the problem could be?

**Comment by TheUltimateCookie** [comment]
I faced this same issue in GCP (App engine). Although I installed chromedriver, it's not detecting it. I'm getting `google-chrome: executable not found in $PATH`. I also got `Scraping Started`.

Any advice?

**Comment by musabgultekin** [comment]
Looking into it

**Comment by musabgultekin** [comment]
@dock-mausbach 
@TheUltimateCookie 

I've installed chromium using this line to my test docker file based on "golang:alpine" and it worked. Could you try? If it works for you too, I'll add it to docs.
```
RUN apk add chromium
```

**Comment by TheUltimateCookie** [comment]
I tried that. It worked for me, but a little too memory intensive for me. Is it possible to integrate with `chromedp/headless-shell`?
This is my current dockerfile
```
FROM golang:1.15-buster as builder

WORKDIR /app
COPY go.* ./
RUN go mod download

COPY . ./

RUN go build -v -o server

FROM chromedp/headless-shell:latest

COPY --from=builder /app/server /app/server

CMD ["/app/server"]
```

**Comment by musabgultekin** [comment]
I saw from headless-shell repo issues that the creators created this to be used as an external chrome instance. Not in the same image as the app. I've tried chromedp/headless-shell to run within the same image, but no luck. That image should be used  as remoteallocator I suppose

**Comment by dock-mausbach** [comment]
Unfortunately `RUN apk add chromium` does not work for me, still get the same error.

**Comment by TheUltimateCookie** [comment]
@dock-mausbach try this
```
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install
```

**Comment by dock-mausbach** [comment]
@TheUltimateCookie thanks! I'm now getting a new error though: 

```
[2021-08-09 16:40:42] [0809/164042.620686:WARNING:resource_bundle.cc(406)] locale_file_path.empty() for locale 
[2021-08-09 16:40:42] [0809/164042.735421:WARNING:resource_bundle.cc(406)] locale_file_path.empty() for locale 
[2021-08-09 16:40:42] [0809/164042.742436:WARNING:resource_bundle.cc(406)] locale_file_path.empty() for locale 
[2021-08-09 16:40:42] [0809/164042.851329:ERROR:address_tracker_linux.cc(214)] Could not bind NETLINK socket: Permission denied (13)
[2021-08-09 16:40:42] [0809/164042.852017:ERROR:file_path_watcher_linux.cc(76)] Failed to read /proc/sys/fs/inotify/max_user_watches
[2021-08-09 16:40:42] 
[2021-08-09 16:40:42] DevTools listening on ws://0.0.0.0:9222/devtools/browser/e6a09d59-1334-4fa3-95a9-c5f27b5ec1d5
[2021-08-09 16:40:43] [0809/164043.036640:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
[2021-08-09 16:40:43] [0809/164043.245311:WARNING:resource_bundle.cc(406)] locale_file_path.empty() for locale 
[2021-08-09 16:40:43] [0809/164043.264633:ERROR:file_path_watcher_linux.cc(76)] Failed to read /proc/sys/fs/inotify/max_user_watches
[2021-08-09 16:40:43] [0809/164043.264868:ERROR:address_tracker_linux.cc(214)] Could not bind NETLINK socket: Permission denied (13)
[2021-08-09 16:40:43] [0809/164043.439618:ERROR:command_buffer_proxy_impl.cc(126)] ContextResult::kTransientFailure: Failed 
```

**Comment by musabgultekin** [comment]
The latest versions of chromedp/headless-shell and geziyor works perfectly. 
Just start the image with:
```docker run -d -p 9222:9222 --rm --name headless-shell chromedp/headless-shell```
And set 
```BrowserEndpoint:   "ws://localhost:9222",```
for the geziyor Options.

**Comment by shurco** [comment]
> The latest versions of chromedp/headless-shell and geziyor works perfectly. Just start the image with: `docker run -d -p 9222:9222 --rm --name headless-shell chromedp/headless-shell` And set `BrowserEndpoint: "ws://localhost:9222",` for the geziyor Options.

Hi,
Does this construction work now?
I tried it on my server and local machine - nothing happens, the BrowserEndpoint parameter is simply ignored.
