### ISSUE TITLE
go.mod: update to chromedp v0.7.4 needed

### ISSUE THREAD

**Issue by albertbronsky** [geziyor/geziyor#30]
Please update `go.mod` to use the latest `chromedp` version (0.7.4 as of now) because there has been a fix (#https://github.com/chromedp/chromedp/commit/1a19982ec5b6d3c474ba51554b0d00e841041dad#diff-3a710ab6a1dd3264a76a1e4c4c3ebcee14762ef3a66f707726e17fd5fa255715) for the bug that prevented using `NewRemoteAllocator` from sibling Docker container.

**Comment by musabgultekin** [comment]
Updated chromedp
https://github.com/geziyor/geziyor/commit/fc67cec165a5c13baa4b74a33977f662c0a39a4d
