### ISSUE TITLE
proxy support?

### ISSUE THREAD

**Issue by KaoriEl** [geziyor/geziyor#34]
Hello, is it possible to somehow work with proxies in your library? I need every request to work through a proxy

**Comment by crazybee47** [comment]
Yes it makes lib more powerful

**Comment by BKirev** [comment]
+1 for being able to set proxy on the fly/before each request/subset of requests.

**Comment by shavit** [comment]
You can configure the client directly. 

```
// Create a client
client := geziyor.NewGeziyor(&geziyor.Options{
 ...

// Here you set the proxy
url, err := url.Parse("socks5://127.0.0.1:9050")
if err != nil {
  panic(err)
}
dialer, err := proxy.FromURL(url, proxy.Direct)
if err != nil {
  panic(err)
}
// This can be added in separate convenient method
client.Client.Transport = &http.Transport{
   Dial: dialer.Dial,
}

client.Start()
```

I didn't use this framework yet, so this doesn't answer how to configure a subset of requests.

**Comment by musabgultekin** [comment]
I've implemented round-robin proxy support. Can anyone review that. https://github.com/geziyor/geziyor/pull/37
If not, I'll merge directly

**Comment by musabgultekin** [comment]
Merged: https://github.com/geziyor/geziyor/pull/37
