### ISSUE TITLE
How to add customize headers while request?

### ISSUE THREAD

**Issue by leopku** [geziyor/geziyor#41]
Like adding `X-My-Custome-Header` in request header?

**Comment by musabgultekin** [comment]
You should create the request with client.NewRequest
And then set the headers
And then use g.Do(req, callback) function to make that request.

2 Ara 2021 Per 09:24 tarihinde Song Liu ***@***.***> şunu
yazdı:

**Comment by leopku** [comment]
It solved. Thank you @musabgultekin .
