### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by TheUltimateCookie** [geziyor/geziyor#42]
I'm trying to scrape 3242 webpages but I'm getting `response: Get "https://www.typeform.com/templates/t/course-evaluation-form-template/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)` for a lot of urls

Any advice?

**Comment by musabgultekin** [comment]
What is the concurrency?

**Comment by TheUltimateCookie** [comment]
using default

**Comment by musabgultekin** [comment]
So its unlimited,
Can you limit the concurrency? If you have 16 gig ram, maybe 20.

**Comment by TheUltimateCookie** [comment]
I using 8 gib ram, so by how much should I limit the currency?

**Comment by musabgultekin** [comment]
Can you try with 10

8 Ara 2021 Çar 22:03 tarihinde TheUltimateCookie ***@***.***>
şunu yazdı:

**Comment by TheUltimateCookie** [comment]
Too late. I tried 20 with 8gib ram in GCP cloud run. Works fine

**Comment by musabgultekin** [comment]
I liked it worked. Great !

9 Ara 2021 Per 09:28 tarihinde TheUltimateCookie ***@***.***>
şunu yazdı:
