### ISSUE TITLE
Cookie cutters and Declarative scrapping

### ISSUE THREAD

**Issue by suntong** [geziyor/geziyor#5]
Many web sites can be scrapped using standard CSS selection without defining fancy Go code to do that. For this, I still like `goscrape`'s _"structured scraper"_ approach. Ref:

https://github.com/andrew-d/goscrape#goscrape

And here is how its scrapping is defined declaratively:

https://github.com/andrew-d/goscrape/blob/d89ba4ccc7f78429613f2a71bc7703c8faf9e8c9/_examples/scrape_hn.go#L15-L26

```go
	config := &scrape.ScrapeConfig{
		DividePage: scrape.DividePageBySelector("tr:nth-child(3) tr:nth-child(3n-2):not([style='height:10px'])"),

		Pieces: []scrape.Piece{
			{Name: "title", Selector: "td.title > a", Extractor: extract.Text{}},
			{Name: "link", Selector: "td.title > a", Extractor: extract.Attr{Attr: "href"}},
			{Name: "rank", Selector: "td.title[align='right']",
				Extractor: extract.Regex{Regex: regexp.MustCompile(`(\d+)`)}},
		},

		Paginator: paginate.BySelector("a[rel='nofollow']:last-child", "href"),
	}
```

Hope `geziyor` can do declarative scrapping using predefined cookie cutters like above as well.

**Comment by musabgultekin** [comment]
That idea is great! I'll look into this in the soonest time.

**Comment by suntong** [comment]
super glad to hear that, looking forward to it...

**Comment by musabgultekin** [comment]
Now I realized you developed that library. Could you help on implementing this feature?

**Comment by suntong** [comment]
Oh, it is not me, `goscrape` is by `andrew-d`, It's so useful and so advanced, that I feel sad to see that it goes unmaintained. I only added some tiny bits on top, and get nowhere to push. :-(

**Comment by musabgultekin** [comment]
Oops, sorry. I get it.

**Comment by musabgultekin** [comment]
Added extractor support on https://github.com/geziyor/geziyor/commit/b000581c3d99fa89523e8b3292f8fd48ab43c648
I'll add new extractors to support something like DividePage and Paginator on goscrape lib.

**Comment by musabgultekin** [comment]
Its adding so much complexity to scraper. Just by using goquery, the process will be much more simple and customizable. I added like goscrape library, but it didn't provide enough value to develop.
Go is simplicity. I tried this but its not simple to learn and use. There will be a lot to learn on this approach. I could try approach like loaders in scrapy. But it won't provide simplicity too.

**Comment by suntong** [comment]
> Its adding so much complexity to scraper... 

Oh, I didn't know. Feel free to close it now, if it is too much for you.

> the process will be much more simple and customizable

Yeah, that's the ultimate goal, and if we can achieve it, then it'd be super. I understand that when developing a library, there is always a trade-off between between simple to implement, and simple to use. Simple to use and customizable most often means much much more effect to put into the library than a simple implementation. 

Again, feel free to close this if it is too much for you.
