### ISSUE TITLE
having issue while installing via go get

### ISSUE THREAD

**Issue by realuser07** [geziyor/geziyor#8]
root@machine:~# go get github.com/geziyor/geziyor
github.com/geziyor/geziyor/export

src/github.com/geziyor/geziyor/export/csv.go:47:15: val.MapRange undefined (type reflect.Value has no field or method MapRange)

**Comment by musabgultekin** [comment]
MapRange method added in Go 1.12. So you need to update go version 1.12
I'll look if there is better solution.

**Comment by musabgultekin** [comment]
Fixed on: https://github.com/geziyor/geziyor/commit/762854e5113a0f8a0c69eed3352f09d45ef19b9e
